config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :attendances
      resources :events
      resources :users

      root to: "attendances#index"
    end
  devise_for :users
  resources :attendances
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete '/users/sign_out', to: 'users#sign_out'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  # Defines the root path route ("/")
  # root "posts#index"
  root 'events#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendances
  has_many :attendees, through: :attendances, source: :user

  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0, divisible_by: 5 }
  validates :title, presence: true, length: { minimum: 5, maximum: 140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  validate :start_date_cannot_be_in_the_past

  private

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Time.now
      errors.add(:start_date, "can't be in the past")
    end
  end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @attendance = Attendance.new(event: @event)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:title, :description, :start_date, :duration, :price, :location, :user_id)
  end

  def require_creator
    @event = Event.find(params[:id])
    unless current_user == @event.user
      flash[:alert] = "Vous n'êtes pas autorisé à accéder à cette page."
      redirect_to events_path
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p>
    <strong>Title:</strong>
    <%= event.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= event.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= event.start_date %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= event.duration %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= event.price %>
  </p>

  <p>
    <strong>location:</strong>
    <%= event.location %>
  </p>

  <p>
    <strong>User:</strong>
    <%= event.user_id %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control", autocomplete: "off" %>
  </div>

  <div class="field">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :start_date, style: "display: block" %>
    <%= form.datetime_field :start_date, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bienvenue sur la page d'accueil</title>
  <%= stylesheet_link_tag 'application' %>
</head>
<body>
  <div class="container">
    <% @events.each do |event| %>
      <div class="card">
        <div class="card-content">
          <h2 class="card-title"><%= event.title %></h2>
          <p class="card-description"><%= event.description %></p>
          <a class="card-link" href="<%= event_path(event) %>">Voir l'événement</a>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "Nouvel événement", new_event_path, class: "btn btn-primary new-event-link" %>
</body>
</html>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Retour aux événements", events_path, class: "btn btn-primary mr-2 mb-2" %>
</div>

app/views/events/show.html.erb
<div class="event-details">
  <% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="card">
    <div class="card-body">
      <%= render @event %>
    </div>
  </div>

  <div class="event-actions mt-3">
    <% unless current_user.admin? || @event.attendees.include?(current_user) %>
      <%= link_to "S'inscrire à cet événement", new_attendance_path(event_id: @event.id), class: "btn btn-primary mr-2 mb-2" %>
    <% end %>

    <% if current_user == @event.user %>
      <%= link_to "Voir les invités", event_attendances_path(@event), class: "btn btn-secondary mr-2 mb-2" %>
    <% end %>

    <%= link_to "Modifier cet événement", edit_event_path(@event), class: "btn btn-warning mr-2 mb-2" %>
    <%= button_to "Supprimer cet événement", @event, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer cet événement ?' }, class: "btn btn-danger mr-2 mb-2" %>
    <%= button_to "Passer commande (NEXT GEN)", checkout_create_path(total: @event.price), class: "btn btn-success mr-2 mb-2", remote: true %>
    <%= link_to "Retour aux événements", events_path, class: "btn btn-primary mr-2 mb-2" %>
  </div>
</div>