config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :attendances
      resources :events
      resources :users

      root to: "attendances#index"
    end
  devise_for :users
  resources :attendances
  resources :events
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  delete '/users/sign_out', to: 'users#sign_out'

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
end

  # Defines the root path route ("/")
  # root "posts#index"
  root 'events#index'
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :send_attendance_notification
  belongs_to :user
  belongs_to :event

  validates :stripe_customer_id, presence: true

  private

  def send_attendance_notification
    UserMailer.attendance_notification(event.user, user).deliver_now

    creator_email = event.user.email
    EventMailer.participant_notification(creator_email).deliver_now
  end
end

app/controllers/admin/attendances_controller.rb
module Admin
  class AttendancesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
     def update
       super
       send_foo_updated_email(requested_resource)
     end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
     def find_resource(param)
       Foo.find_by!(slug: param)
     end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
     def resource_params
       params.require(resource_class.model_name.param_key).
         permit(dashboard.permitted_attributes(action_name)).
         transform_values { |value| value == "" ? nil : value }
     end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
    def show_association_scope
      return super unless resource.is_a?(Event)
      resource.attendances
    end
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: %i[ show edit update destroy ]

  # GET /attendances or /attendances.json
  def index
    @event = Event.find(params[:event_id])
    @attendees = @event.attendees
  end
  # GET /attendances/1 or /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new(event_id: params[:event_id])
  end

  # GET /attendances/1/edit
  def edit
  end

  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully created." }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1 or /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to attendance_url(@attendance), notice: "Attendance was successfully updated." }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1 or /attendances/1.json
  def destroy
    @attendance.destroy!

    respond_to do |format|
      format.html { redirect_to attendances_url, notice: "Attendance was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def attendance_params
      params.require(:attendance).permit(:user_id, :event_id)
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/views/attendances/_attendance.html.erb
<div id="<%= dom_id attendance %>">
  <p>
    <strong>User:</strong>
    <%= attendance.user_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= attendance.event_id %>
  </p>

</div>

app/views/attendances/_form.html.erb
<%= form_with(model: attendance) do |form| %>
  <% if attendance.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
        <% attendance.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :event_id, style: "display: block" %>
    <%= form.text_field :event_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/attendances/edit.html.erb
<h1>Editing attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Show this attendance", @attendance %> |
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Attendances</h1>

<div id="attendances">
  <% @attendances.each do |attendance| %>
    <%= render attendance %>
    <p>
      <%= link_to "Show this attendance", attendance %>
    </p>
  <% end %>
  <% if current_user == @event.user %>
  <%= link_to "Modifier l'événement", edit_event_path(@event), class: "btn btn-primary" %>
  <%= button_to "Supprimer l'événement", @event, method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet événement ?" }, class: "btn btn-danger" %>
<% end %>
</div>

<%= link_to "New attendance", new_attendance_path %>

app/views/attendances/new.html.erb
<h1>New attendance</h1>

<%= render "form", attendance: @attendance %>

<br>

<div>
  <%= link_to "Back to attendances", attendances_path %>
</div>

app/views/attendances/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @attendance %>

<div>
  <%= link_to "Edit this attendance", edit_attendance_path(@attendance) %> |
  <%= link_to "Back to attendances", attendances_path %>

  <%= button_to "Destroy this attendance", @attendance, method: :delete %>
</div>